name = "Bannai-Bannai-Stanton_Theorem"
version = "0.1.0"
description = "Formalisation of the Bannai-Bannai-Stanton theorem bound on distance sets"
authors = ["Antoine du Fresne von Hohenesche"]
license = "Apache-2.0"
keywords = ["math", "geometry", "combinatorics", "distance-sets"]
defaultTargets = ["Project"]

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Project"
